### ISSUE TITLE
Doesn't compile on clang 18.1

### ISSUE THREAD

**Issue by hoyhoy** [mgehre/xunused#14]
```
[ 50%] Building CXX object CMakeFiles/xunused.dir/main.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -I/opt/llvm18/include -I/opt/include -I /opt/openssl-3.2.1/include -O3 -march=native -funroll-loops -finline-functions -mtune=native -Wno-everything -O3 -DNDEBUG -std=gnu++17 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk -mmacosx-version-min=14.4 -fcolor-diagnostics   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT CMakeFiles/xunused.dir/main.cpp.o -MF CMakeFiles/xunused.dir/main.cpp.o.d -o CMakeFiles/xunused.dir/main.cpp.o -c /xunused/main.cpp
/xunused/main.cpp:178:37: error: no member named 'isPure' in 'clang::CXXMethodDecl'
        if (MD->isVirtual() && !MD->isPure() && MD->size_overridden_methods())
                                ~~  ^
1 error generated.
make[2]: *** [CMakeFiles/xunused.dir/build.make:76: CMakeFiles/xunused.dir/main.cpp.o] Error 1
make[2]: Leaving directory '/xunused'
make[1]: *** [CMakeFiles/Makefile2:218: CMakeFiles/xunused.dir/all] Error 2
make[1]: Leaving directory '/xunused'
make: *** [Makefile:136: all] Error 2

```

**Comment by hoyhoy** [comment]
It's `isPureVirtual()` now.

**Comment by mgehre** [comment]
Thanks for the report and letting me know how the function is called now. I just merged a PR with an update.

**Comment by hoyhoy** [comment]
Yeah, I can't actually get it to run on clang 18.  After I fixed that, I ran into include problems.  I tried adding various things to extra_arg field, but that didn't work either.  Why doesn't it pull the `-isystem` from the clang defaults?

**Comment by mgehre** [comment]
Hm, do you have a reproducer? What is the error you get?

**Comment by hoyhoy** [comment]
It claims it can't find `stdargs.h` and `libc++`.  I tried this:

`xunused -extra-arg="-I/opt/llvm18/lib/clang/18/include" -extra-arg="-stdlib=libc++" -extra-arg="-std=c++20" compile_commands.json `, but that didn't work either.  I also tried addiing all the args in one `-extra-arg`.  Wasn't sure which syntax was right if you have eleventy billion args.

clang _knows_ where all of the headers are.  I would think all of the following should be the default.  Also, it should pull in the system config defaults as well (`/opt/llvm18/etc/x86_64-apple-darwin23.4.0-clang.cfg` for me)

```
clang -v ~/backup/main.c
clang version 18.1.1
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /opt/llvm18/bin
Configuration file: /opt/llvm18/etc/x86_64-apple-darwin23.4.0-clang.cfg
System configuration file directory: /opt/llvm18/etc
 "/opt/llvm18/bin/clang-18" -cc1 -triple x86_64-apple-macosx14.4.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -ffp-contract=on -fno-rounding-math -funwind-tables=2 -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -fbuiltin-headers-in-system-modules -target-cpu penryn -tune-cpu generic -debugger-tuning=lldb -fdebug-compilation-dir=. -target-linker-version 1053.12 -v -fcoverage-compilation-dir=. -resource-dir /opt/llvm18/lib/clang/18 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -internal-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /opt/llvm18/lib/clang/18/include -internal-externc-isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -fmax-type-align=16 -fcolor-diagnostics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /var/folders/sg/by4ymb_1491658nz5rdt1k940000gn/T/main-79ed0c.o -x c test.c
clang -cc1 version 18.1.1 based upon LLVM 18.1.1 default target x86_64-apple-darwin23.4.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /opt/llvm18/lib/clang/18/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/opt/llvm18/bin/ld64.lld" -demangle -no_deduplicate -dynamic -arch x86_64 -platform_version macos 14.4.0 14.4.0 -L /opt/llvm18/bin/../lib -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mllvm -enable-linkonceodr-outlining -o a.out -L/opt/llvm18/lib/darwin -rpath /opt/llvm18/lib /var/folders/sg/by4ymb_1491658nz5rdt1k940000gn/T/main-79ed0c.o -lSystem /opt/llvm18/lib/clang/18/lib/darwin/libclang_rt.osx.a
```

**Comment by hoyhoy** [comment]
```
$ xunused -extra-arg="-I/opt/llvm18/lib/clang/18/include" -extra-arg="-stdlib=libc++" -extra-arg="-std=c++20" compile_commands.json 2>&1  | grep "error: " | perl -p -e 's,/Users/jperrie[^:]+:,,'
error: error: error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]error: 
error: 
error: error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]
error: error: invalid argument '-std=c++20' not allowed with 'C'error: error: invalid argument '-std=c++20' not allowed with 'C'invalid argument '-std=c++20' not allowed with 'C'
error: 
error: invalid argument '-std=c++20' not allowed with 'C'error: invalid argument '-std=c++20' not allowed with 'C'
error: invalid argument '-std=c++20' not allowed with 'C'
/opt/llvm18/bin/../include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
/opt/llvm18/bin/../include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: template argument for template type parameter must be a type
/opt/llvm18/bin/../include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
/opt/llvm18/bin/../include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
/opt/llvm18/bin/../include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
/opt/llvm18/bin/../include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
/opt/llvm18/bin/../include/c++/v1/cstddef:46:5: error: <cstddef> tried including <stddef.h> but didn't find libc++'s <stddef.h> header.           This usually means that your header search paths are not configured properly.           The header search paths should contain the C++ Standard Library headers before           any C Standard Library, and you are probably using compiler flags that make that           not be the case.
/opt/llvm18/bin/../include/c++/v1/cstddef:59:9: error: no member named 'nullptr_t' in the global namespace
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: template argument for template type parameter must be a type
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: template argument for template type parameter must be a type
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?
/opt/llvm18/bin/../include/c++/v1/__type_traits/is_null_pointer.h:26:28: error: template argument for template type parameter must be a type
```
